### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by pchero** [JonnyWhatshisface/libwebsock#9]
Hi, 

I would like know, is this library under the GPL license or LGPL license?
Because there's 2 license files in the project..

Thank you.

Kind regards,
Sungtae

**Comment by ac000** [comment]
Good question.

The original license for this was GPL 3.0. @JonnyWhatshisface seems to have changed/added the license to/for LGPL 3.0.

Now while the LGPL does make more sense for this, I'm not sure he's actually allowed to do that as Payden was the copyright holder. Of course IANAL.

Then there is libwebsock2 which seems to be back under the GPL...

**Comment by pchero** [comment]
Thank you for your reply. I was confused that too, because once it published to GPL, it doesn't allow to move any other License...

Okay, thank you for your answer. Now I'm clear. :)
And thank you for sharing your good project.
